name: CodeForgeZero DevSecOps Pipeline

on: [push] # Se dispara cada vez que alguien sube código

jobs:
  auditoria-ia:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar el código nuevo
        uses: actions/checkout@v3

      - name: Instalar herramientas
        run: pip install requests

      - name: Consultar al Patovica (Render)
        run: |
          python -c "
          import requests, sys
          
          # Le mandamos un código 100% optimizado en RAM para que el patovica no se queje
          codigo = '''
          def sumar_numeros():
              return (i * 2 for i in range(1000000))
          '''
          
          url = 'https://codeforgezero-backend.onrender.com/api/cicd/analyze'
          
          print('🚀 Enviando código PERFECTO a la IA de CodeForgeZero...')
          res = requests.post(url, json={'code': codigo, 'language': 'python'})
          data = res.json()
          
          ia_respuesta = data.get('webhook_response', {})
          
          if ia_respuesta.get('aprobado') == False:
              print('❌ CÓDIGO RECHAZADO POR LA IA')
              sys.exit(1)
          else:
              print('✅ PATOVICA FELIZ. Código aprobado, pasando a producción.')
          "
        shell: bash